CC=gcc
FLAGS=-g -Wall -Werror
OBJ= server
LIBS= -pthread

all:  $(OBJ)
	@echo "***************************"
	@echo "Compilation successfully!"
	@echo ""

clean:
	find . -exec touch {} \;
	@echo "***************************"
	@echo "Deleted files!"
	@echo  ""

